language: java
jdk:
- oraclejdk7
script: mvn clean package
notifications:
  email: true
skip_cleanup: true
after_success: curl -u $FTP_USER:$FTP_PASSWORD -T /home/travis/build/muchencute/mobiledata-core/target/mobiledata.war ftp://$FTP_IP/webapps/